language: java

jdk:
  - oraclejdk11

cache:
  directories:
    - $HOME/.m2

before_install:
  - curl -L https://git.io/get_helm.sh | bash
  - helm init --client-only

install: /bin/true

script:
  - ./mvnw verify -B
  - |
      if [ "$TRAVIS_BRANCH" = "master" ]; then
        cp README.md charts
        cd charts
        helm repo index .
        ls -ltr
      fi

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: charts
  target_branch: gh-pages
  verbose: true
  skip_cleanup: true
  keep_history: true
  on:
    branch: master

dist: bionic
