{{- if .Values.ha.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "artemis.fullname" . }}-backup
  labels:
{{ include "artemis.labels.backup" . | indent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: 61616
      targetPort: netty
      protocol: TCP
      name: netty
    - port: 5672
      targetPort: amqp
      name: amqp
    - port: 61613
      targetPort: stomp
      name: stomp
    - port: 1883
      targetPort: mqtt
      name: mqtt
  selector:
    app.kubernetes.io/name: {{ include "artemis.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/ha: backup
{{- end }}
