apiVersion: v1
kind: Service
metadata:
  name: {{ include "artemis.fullname" . }}
  labels:
{{ include "artemis.labels.live" . | indent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 61616
      targetPort: netty
      protocol: TCP
      name: netty
    - port: 5672
      targetPort: amqp
      name: amqp
    - port: 61613
      targetPort: stomp
      name: stomp
    - port: 1883
      targetPort: mqtt
      name: mqtt
    {{- if .Values.metrics.enabled }}
    - port: 9404
      targetPort: prometheus
      name: prometheus
    {{- end }}

  selector:
    app.kubernetes.io/name: {{ include "artemis.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Values.ha.enabled }}
    app.kubernetes.io/ha: live
    {{- end }}
