---
{{- if .Values.ha.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "artemis.fullname" . }}-backup
spec:
  selector:
    matchLabels:
      {{- include "artemis.labels.backup" . | nindent 6 }}
  serviceName: {{ include "artemis.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  podManagementPolicy: Parallel
  template:
    metadata:
    {{- if .Values.metrics.enabled }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9404"
    {{- end }}
      labels:
        {{- include "artemis.labels.backup" . | nindent 8 }}
    spec:
      {{- include "artemis.statefulset.spec" . | nindent 6 }}
          - key: broker-ha-backup.xml
            path: broker-00.xml
          - key: ha-backup.xml
            path: ha-backup.xml
          - key: connectors.xml
            path: connectors.xml
  {{- include "artemis.statefulset.volumeclaim" . | nindent 2 }}
{{- end }}
