name: Verify & deploy charts

on: push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.2

      - name: Run chart-testing (lint)
        run: helm lint charts/artemis -f test/values.yaml

      - name: Run chart-testing (template)
        run: helm template charts/artemis -f test/values.yaml

      - name: Run chart-releaser
        if: github.ref == 'refs/heads/master'
        uses: helm/chart-releaser-action@v1.2.1
        with:
          charts_repo_url: https://deviceinsight.github.io/activemq-artemis-helm
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
